/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelRoupa;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ricardo Mota
 */
public class ViewCadastroRoupaClima extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroRoupaClima
     */
    ModelRoupa modelRoupa;
    public ViewCadastroRoupaClima(ModelRoupa roupa) {
        modelRoupa = roupa;
        initComponents();
    }

    private ViewCadastroRoupaClima() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupClima = new javax.swing.ButtonGroup();
        jRadioButtonSol = new javax.swing.JRadioButton();
        jRadioButtonSeco = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        lblClima = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jRadioButtonNublado = new javax.swing.JRadioButton();
        jRadioButtonChuva = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupClima.add(jRadioButtonSol);
        jRadioButtonSol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonSol.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSol.setSelected(true);
        jRadioButtonSol.setText("Sol");
        jRadioButtonSol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSolActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, 30));

        buttonGroupClima.add(jRadioButtonSeco);
        jRadioButtonSeco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonSeco.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeco.setText("Seco");
        jRadioButtonSeco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jRadioButtonSeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 208, 80, 30));

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-proximo.png"))); // NOI18N
        btnNext.setText("Próximo");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 190, 50));

        lblClima.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblClima.setForeground(new java.awt.Color(255, 255, 255));
        lblClima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClima.setText("Escolha o Clima");
        lblClima.setMaximumSize(new java.awt.Dimension(250, 40));
        lblClima.setMinimumSize(new java.awt.Dimension(250, 40));
        lblClima.setPreferredSize(new java.awt.Dimension(330, 40));
        getContentPane().add(lblClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 40));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 50));

        buttonGroupClima.add(jRadioButtonNublado);
        jRadioButtonNublado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonNublado.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButtonNublado.setText("Nublado");
        getContentPane().add(jRadioButtonNublado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        buttonGroupClima.add(jRadioButtonChuva);
        jRadioButtonChuva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonChuva.setForeground(new java.awt.Color(240, 240, 240));
        jRadioButtonChuva.setText("Chuva");
        getContentPane().add(jRadioButtonChuva, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/banner-vestindo-certo-15.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));

        setSize(new java.awt.Dimension(450, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSolActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        //AQUI DEVE SER GRAVADO A ROUPA
        if(jRadioButtonSol.isSelected()){;
            modelRoupa.setFkClima(1);
        }else if(jRadioButtonChuva.isSelected()){
            modelRoupa.setFkClima(2);
        }else if(jRadioButtonNublado.isSelected()){
            modelRoupa.setFkClima(3);
        }else if(jRadioButtonSeco.isSelected()){
            modelRoupa.setFkClima(4);
        }
        
        ViewCadastroRoupaResultado resultado;
        try {
            resultado = new ViewCadastroRoupaResultado(modelRoupa);
            resultado.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(ViewCadastroRoupaClima.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        ViewCadastroRoupaEvento evento = new ViewCadastroRoupaEvento(modelRoupa);
        evento.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroRoupaClima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroupClima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonChuva;
    private javax.swing.JRadioButton jRadioButtonNublado;
    private javax.swing.JRadioButton jRadioButtonSeco;
    private javax.swing.JRadioButton jRadioButtonSol;
    private javax.swing.JLabel lblClima;
    // End of variables declaration//GEN-END:variables
}
