/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelRoupa;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Ricardo Mota
 */
public class ViewCadastroRoupaResultado extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroRoupaResultado
     */
    ModelRoupa modelRoupa;
    public ViewCadastroRoupaResultado(ModelRoupa roupa) throws IOException{
        modelRoupa = roupa;
        initComponents();
        
        //SET IMAGE
        String imagePath = new File(".").getCanonicalPath()+"/src/ImagesUsuarios/";
        ImageIcon image = new ImageIcon(imagePath+modelRoupa.getImagem());
        jLabelImagem.setIcon(image);
        
        
        //SET LOCAL
        switch (modelRoupa.getFk_local()) {
            case 1:
                jLabelLocal.setText("Cidade Grande");
                break;
            case 2:
                jLabelLocal.setText("Cidade Interior");
                break;
            case 3:
                jLabelLocal.setText("Chácara / Sítio");
                break;
            default:
                break;
        }
        
        //SET EVENTO
        switch (modelRoupa.getFk_evento()) {
            case 1:
                jLabelEvento.setText("Faculdade");
                break;
            case 2:
                jLabelEvento.setText("Trabalho");
                break;
            case 3:
                jLabelEvento.setText("Festa");
                break;
            case 4:
                jLabelEvento.setText("Balada");
                break;
            case 5:
                jLabelEvento.setText("Casamento");
                break;
            case 6:
                jLabelEvento.setText("Academia");
                break;
            default:
                break;
        }
        
        //SET CLIMA
        switch (modelRoupa.getFk_clima()) {
            case 1:
                jLabelClima.setText("Sol");
                break;
            case 2:
                jLabelClima.setText("Chuva");
                break;
            case 3:
                jLabelClima.setText("Nublado");
                break;
            case 4 :
                jLabelClima.setText("Seco");
                break;
            default:
                break;
        }
    }

    private ViewCadastroRoupaResultado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClima = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jLabelEvento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClima.setText("CLIMA");
        getContentPane().add(jLabelClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 210, 20));

        jLabelImagem.setText("IMAGEM");
        getContentPane().add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 240));

        jLabelLocal.setText("LOCAL");
        getContentPane().add(jLabelLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 260, 20));

        jLabelEvento.setText("EVENTO");
        getContentPane().add(jLabelEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 230, 20));

        setSize(new java.awt.Dimension(466, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroRoupaResultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelEvento;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelLocal;
    // End of variables declaration//GEN-END:variables
}
