/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerLook;
import Model.ModelRoupa;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author internet
 */
public class ViewLookGerado extends javax.swing.JFrame {

    /**
     * Creates new form ViewLookGerado
     */
    
    ModelRoupa modelRoupa;
    public ViewLookGerado(ModelRoupa roupa) throws IOException {
        initComponents();
        ControllerLook look = new ControllerLook();
        String imagePath = new File(".").getCanonicalPath()+"/src/ImagesUsuarios/";
        
        ModelRoupa modelRoupaTipo01 = new ModelRoupa();
        modelRoupaTipo01 = roupa;
        modelRoupaTipo01.setFkTipo(1);
        //JOptionPane.showMessageDialog(null, modelRoupaTipo01.getFkTipo());
        ModelRoupa novoLook01 = look.gerarLook(modelRoupaTipo01);
        //SET IMAGE
        ImageIcon image01 = new ImageIcon(imagePath+novoLook01.getImagem());
        jLabelImagem01.setIcon(image01);
                
        ModelRoupa modelRoupaTipo02 = new ModelRoupa();
        modelRoupaTipo02 = roupa;
        modelRoupaTipo02.setFkTipo(2);
        //JOptionPane.showMessageDialog(null, modelRoupaTipo02.getFkTipo());
        ModelRoupa novoLook02 = look.gerarLook(modelRoupaTipo02);
        ImageIcon image02 = new ImageIcon(imagePath+novoLook02.getImagem());
        jLabelImagem02.setIcon(image02);        
    }

    private ViewLookGerado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelImagem01 = new javax.swing.JLabel();
        jLabelImagem02 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOOK GERADO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltarMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-voltar.png"))); // NOI18N
        btnVoltarMenu.setText("Voltar");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 190, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Este é sua combinação");
        jLabel1.setFocusTraversalPolicyProvider(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(330, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));
        getContentPane().add(jLabelImagem01, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 240, 210));
        getContentPane().add(jLabelImagem02, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 240, 210));

        btnGerar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGerar.setText("Gerar Novo");
        btnGerar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGerarStateChanged(evt);
            }
        });
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 190, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        ViewEscolherClima clima = new ViewEscolherClima(modelRoupa);
        clima.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed

        ViewEscolherLocal local = new ViewEscolherLocal();
        local.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnGerarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGerarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLookGerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLookGerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLookGerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLookGerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLookGerado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagem01;
    private javax.swing.JLabel jLabelImagem02;
    // End of variables declaration//GEN-END:variables
}
