/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelRoupa;

/**
 *
 * @author internet
 */
public class ViewEscolherLocal extends javax.swing.JFrame {

    /**
     * Creates new form ViewEscolherLocal
     */
    ModelRoupa modelRoupa = new ModelRoupa();
    public ViewEscolherLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLocal = new javax.swing.ButtonGroup();
        jRadioButtonCidadeGrande = new javax.swing.JRadioButton();
        jRadioButtonCidadeInterior = new javax.swing.JRadioButton();
        bntEscolherEvento = new javax.swing.JButton();
        jRadioButtonChacaraSitio = new javax.swing.JRadioButton();
        btnVoltarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESCOLHA DO LOCAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupLocal.add(jRadioButtonCidadeGrande);
        jRadioButtonCidadeGrande.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonCidadeGrande.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCidadeGrande.setSelected(true);
        jRadioButtonCidadeGrande.setText("Cidade Grande");
        jRadioButtonCidadeGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCidadeGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCidadeGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 30));

        buttonGroupLocal.add(jRadioButtonCidadeInterior);
        jRadioButtonCidadeInterior.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonCidadeInterior.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCidadeInterior.setText("Cidade Interior");
        getContentPane().add(jRadioButtonCidadeInterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 30));

        bntEscolherEvento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bntEscolherEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-proximo.png"))); // NOI18N
        bntEscolherEvento.setText("Próximo");
        bntEscolherEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEscolherEventoActionPerformed(evt);
            }
        });
        getContentPane().add(bntEscolherEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 190, 50));

        buttonGroupLocal.add(jRadioButtonChacaraSitio);
        jRadioButtonChacaraSitio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonChacaraSitio.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonChacaraSitio.setText("Chácara / Sítio");
        getContentPane().add(jRadioButtonChacaraSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 30));

        btnVoltarMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-voltar.png"))); // NOI18N
        btnVoltarMenu.setText("Voltar");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha o Local");
        jLabel1.setPreferredSize(new java.awt.Dimension(330, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/banner-vestindo-certo-10.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCidadeGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCidadeGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCidadeGrandeActionPerformed

    private void bntEscolherEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEscolherEventoActionPerformed

        if(jRadioButtonCidadeGrande.isSelected()){;
            modelRoupa.setFkLocal(1);
        }else if(jRadioButtonCidadeInterior.isSelected()){
            modelRoupa.setFkLocal(2);
        }else if(jRadioButtonChacaraSitio.isSelected()){
            modelRoupa.setFkLocal(3);
        }
        
        ViewEscolherEvento evento = new ViewEscolherEvento(modelRoupa);
        evento.setVisible(true);
        dispose();
    }//GEN-LAST:event_bntEscolherEventoActionPerformed

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed

        ViewMenu menu = new ViewMenu();;
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEscolherLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEscolherLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEscolherLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEscolherLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEscolherLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEscolherEvento;
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.ButtonGroup buttonGroupLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonChacaraSitio;
    private javax.swing.JRadioButton jRadioButtonCidadeGrande;
    private javax.swing.JRadioButton jRadioButtonCidadeInterior;
    // End of variables declaration//GEN-END:variables
}
