/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelRoupa;
import javax.swing.JOptionPane;

/**
 *
 * @author terced-ricardoh
 */
public class ViewCadastroRoupaLocal extends javax.swing.JFrame {
    /**
     * Creates new form ViewCadastroRoupaLocal
     * @param modelRoupa
     */
    ModelRoupa modelRoupa;
    public ViewCadastroRoupaLocal(ModelRoupa roupa) {
        modelRoupa = roupa;
        initComponents();
        lblTesteNome.setText(modelRoupa.getImagem());
    }

    private ViewCadastroRoupaLocal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLocal = new javax.swing.ButtonGroup();
        lblTesteNome = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jRadioButtonCidadeGrande = new javax.swing.JRadioButton();
        jRadioButtonCidadeInterior = new javax.swing.JRadioButton();
        jRadioButtonChacaraSitio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnVoltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblTesteNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, 25));

        jButtonNext.setText("Próximo");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 180, 50));

        buttonGroupLocal.add(jRadioButtonCidadeGrande);
        jRadioButtonCidadeGrande.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonCidadeGrande.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCidadeGrande.setSelected(true);
        jRadioButtonCidadeGrande.setText("Cidade Grande");
        jRadioButtonCidadeGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCidadeGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCidadeGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        buttonGroupLocal.add(jRadioButtonCidadeInterior);
        jRadioButtonCidadeInterior.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonCidadeInterior.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCidadeInterior.setText("Cidade Interior");
        getContentPane().add(jRadioButtonCidadeInterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        buttonGroupLocal.add(jRadioButtonChacaraSitio);
        jRadioButtonChacaraSitio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButtonChacaraSitio.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonChacaraSitio.setText("Chácara / Sítio");
        getContentPane().add(jRadioButtonChacaraSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha o Local");
        jLabel1.setPreferredSize(new java.awt.Dimension(330, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 450, -1));

        btnVoltarMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-voltar.png"))); // NOI18N
        btnVoltarMenu.setText("Voltar");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, 50));

        setSize(new java.awt.Dimension(466, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        //JOptionPane.showMessageDialog(null, modelRoupa.getImagem());
                
        if(jRadioButtonCidadeGrande.isSelected()){;
            modelRoupa.setFkLocal(1);
        }else if(jRadioButtonCidadeInterior.isSelected()){
            modelRoupa.setFkLocal(2);
        }else if(jRadioButtonChacaraSitio.isSelected()){
            modelRoupa.setFkLocal(3);
        }
        
        ViewCadastroRoupaEvento next = new ViewCadastroRoupaEvento(modelRoupa);
        next.setVisible(true);
        dispose();     
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jRadioButtonCidadeGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCidadeGrandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCidadeGrandeActionPerformed

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        ViewCadastroRoupa cadastroRoupa = new ViewCadastroRoupa();
        cadastroRoupa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroRoupaLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.ButtonGroup buttonGroupLocal;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonChacaraSitio;
    private javax.swing.JRadioButton jRadioButtonCidadeGrande;
    private javax.swing.JRadioButton jRadioButtonCidadeInterior;
    private javax.swing.JLabel lblTesteNome;
    // End of variables declaration//GEN-END:variables
}
