/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerRoupa;
import Model.ModelRoupa;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Mota
 */
public class ViewCadastroRoupaResultado extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroRoupaResultado
     */
    ModelRoupa modelRoupa;
    public ViewCadastroRoupaResultado(ModelRoupa roupa) throws IOException{
        modelRoupa = roupa;
        initComponents();
        
        //SET IMAGE
        String imagePath = new File(".").getCanonicalPath()+"/src/ImagesUsuarios/";
        ImageIcon image = new ImageIcon(imagePath+modelRoupa.getImagem());
        jLabelImagem.setIcon(image);
        
        this.jFrameSetLocal();
        this.jFrameSetEvento();
        this.jFrameSetClima();
        this.jFrameSetTipo();
    }
    
    private void jFrameSetTipo(){
        //SET TIPO
        switch (modelRoupa.getFkTipo()) {
            case 1:
                jLabelTipo.setText("Tipo 01");
                break;
            case 2:
                jLabelTipo.setText("Tipo 02");
                break;
            default:
                break;
        }    
    }
    
    private void jFrameSetLocal(){
        //SET LOCAL
        switch (modelRoupa.getFkLocal()) {
            case 1:
                jLabelLocal.setText("Cidade Grande");
                break;
            case 2:
                jLabelLocal.setText("Cidade Interior");
                break;
            case 3:
                jLabelLocal.setText("Chácara / Sítio");
                break;
            default:
                break;
        }    
    }
    
    private void jFrameSetEvento(){  
        //SET EVENTO
        switch (modelRoupa.getFkEvento()) {
            case 1:
                jLabelEvento.setText("Faculdade");
                break;
            case 2:
                jLabelEvento.setText("Trabalho");
                break;
            case 3:
                jLabelEvento.setText("Festa");
                break;
            case 4:
                jLabelEvento.setText("Balada");
                break;
            case 5:
                jLabelEvento.setText("Casamento");
                break;
            case 6:
                jLabelEvento.setText("Academia");
                break;
            default:
                break;
        }  
    }
    
    private void jFrameSetClima(){
        //SET CLIMA
        switch (modelRoupa.getFkClima()) {
            case 1:
                jLabelClima.setText("Sol");
                break;
            case 2:
                jLabelClima.setText("Chuva");
                break;
            case 3:
                jLabelClima.setText("Nublado");
                break;
            case 4 :
                jLabelClima.setText("Seco");
                break;
            default:
                break;
        }
    }

    private ViewCadastroRoupaResultado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClima = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jLabelEvento = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblClima = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REVISÃO DA ROUPA");
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClima.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelClima.setForeground(new java.awt.Color(240, 240, 240));
        jLabelClima.setText("CLIMA:");
        getContentPane().add(jLabelClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 190, 20));
        getContentPane().add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 240, 210));

        jLabelLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLocal.setForeground(new java.awt.Color(240, 240, 240));
        jLabelLocal.setText("LOCAL:");
        getContentPane().add(jLabelLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, 20));

        jLabelEvento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelEvento.setForeground(new java.awt.Color(240, 240, 240));
        jLabelEvento.setText("EVENTO:");
        getContentPane().add(jLabelEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 180, 20));

        btnGravar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-gravar.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 190, 50));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone-voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 50));

        lblClima.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblClima.setForeground(new java.awt.Color(255, 255, 255));
        lblClima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClima.setText("Revisão da Roupa");
        lblClima.setMaximumSize(new java.awt.Dimension(250, 40));
        lblClima.setMinimumSize(new java.awt.Dimension(250, 40));
        lblClima.setPreferredSize(new java.awt.Dimension(330, 40));
        getContentPane().add(lblClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 40));

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelTipo.setText("TIPO:");
        getContentPane().add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 190, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/banner-vestindo-certo-13.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(466, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            ControllerRoupa storeRoupa = new ControllerRoupa();
            Boolean controle = storeRoupa.storeRoupa(modelRoupa);
            if(controle){
                JOptionPane.showMessageDialog(null, "Roupa cadastrada com sucesso.");
                ViewMenu menu = new ViewMenu();
                menu.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Algo deu errado, tente novamente.");
                ViewMenu menu = new ViewMenu();
                menu.setVisible(true);
                dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        ViewCadastroRoupaEvento evento = new ViewCadastroRoupaEvento(modelRoupa);
        evento.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRoupaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroRoupaResultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelEvento;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel lblClima;
    // End of variables declaration//GEN-END:variables
}
